---

- hosts: local
#   become: yes
#   become_method: sudo
  roles:
    - brew
    - ruby
    - python
    - xcode

  tasks:
    - name: Restart Mac
      shell: shutdown -r now
      become_method: sudo
