---

- hosts: local
#   become: yes
#   become_method: sudo
  roles:
#     - brew
     - xcode
#   tasks:
#     - name: ensure homebrew is updated
#       homebrew:
#       state: latest
#       update_homebrew: yes
#  tasks:
#	homebrew:
